# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Checkout submodules
      uses: snickerbockers/submodules-init@v4

    - name: Install npm dependencies
      run: npm install
      working-directory: .

    - name: JS
      run: npm run build
      working-directory: .

    - name: Deploy to uberspace
      run: rsync -e ssh -azvhP -r . uberspace:/var/www/virtual/guido/exhibition.mixing-senses.art/
      working-directory: ./web/public
